### ISSUE TITLE
v0.1.0-rc0 published to hex

### ISSUE THREAD

**Issue by starbelly** [ElMaxo/brod_gssapi#17]
Opening this issue as a way for everyone to stay on the same page. 

Have published brod_gssapi v0.1.0-rc0 to hex, HCA will begin vetting this today or tomorrow.  Has there been other vetting? 

A PR #16 has been opened to switch to using to git for fetching the version to use when publishing for tags. I'm ok with hard code too (normally what I do tbh).  If we do stick with git vsn via tags, then our tags must conform to semantic versioning (note how the current tags do not). 

@kjellwinblad  or @zmstone  since I do not have access to create tags (I believe), can you create one an v0.1.0-rc0 tag? 

Finally, I'll add you two and Vikas as owners on hex for this package right now.

**Comment by zmstone** [comment]
Hi.
I merged #16 and tagged (pushed) `v1.0.0`.
Have not yet published it to hex though,
Please let me know if you feel comfortable (or not) publishing `v1.0.0` at the current state.

If yes, I'll publish it to hex
If no, I'll delete this tag and use `v0.1.0-rc0` for the git tag.

**Comment by zmstone** [comment]
should probably finalise the `v2.0.0` release for `sasl_auth` here ?
https://github.com/kafka4beam/brod_gssapi/blob/92b7d9a78ee16861f48a36065ab197237ca55922/rebar.config#L18

**Comment by starbelly** [comment]
@zmstone Yes, precisely when we get done vetting at our company, we will bump sasl auth to 2.0.0. 

We had defer testing until next week. Will report back ASAP.

**Comment by zmstone** [comment]
Just remembered there was a bug fix in sasl_auth, which resulted in a wrong version bump to `v2.0.1`, should have been `v2.0.0-rc3` instead.

Deleted the v1.0.0 tag for brod_gssapi. and pushed a `v0.1.0-rc0` tag to keep in sync with hex.pm 
also sent a PR to pin the correct version of sasl_auth: https://github.com/kafka4beam/brod_gssapi/pull/18

**Comment by starbelly** [comment]
@zmstone I have published brod_gssapi v0.1.0 to hexpm. Could you merge https://github.com/kafka4beam/brod_gssapi/pull/20 and tag that master as v0.1.0 after it is merged?

**Comment by starbelly** [comment]
n/m, see if I had rights to do this. Tag created and closing this now :)
